USE tutorial;
CREATE TABLE `SYS_USER_LOG` (
    `ID` BIGINT(20)  NOT NULL  COMMENT '主键',
    `USER_ID` BIGINT(20)  DEFAULT NULL  COMMENT '用户ID',
    `VISIT_TYPE` VARCHAR(50)  DEFAULT NULL  COMMENT '访问类型',
    `VISIT_ID` BIGINT(20)  DEFAULT NULL  COMMENT '访问对象的ID',
    `VISIT_TIME` DATETIME  DEFAULT NULL  COMMENT '访问时间',
    `ROW_VERSION` BIGINT(20)  DEFAULT NULL  COMMENT '行版本',
    `IS_DELETED` TINYINT(1)  DEFAULT NULL  COMMENT '是否已删除',
    `CREATED_BY` BIGINT(20)  NOT NULL  COMMENT '创建用户',
    `CREATION_TIME` DATETIME  NOT NULL  COMMENT '创建时间',
    `LAST_UPDATED_BY` BIGINT(20)  DEFAULT NULL  COMMENT '最后更新用户',
    `LAST_UPDATE_TIME` DATETIME  DEFAULT NULL  COMMENT '最后更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户行为日志';