USE tutorial;
CREATE TABLE `SYS_USER` (
    `ID` BIGINT(20)  NOT NULL  COMMENT '主键',
    `NAME` VARCHAR(50)  DEFAULT NULL  COMMENT '昵称',
    `MOBILE` VARCHAR(20)  DEFAULT NULL  COMMENT '手机号',
    `MOBILE_BIND` TINYINT(1) DEFAULT NULL COMMENT '手机号是否已绑定',
    `MAIL` VARCHAR(100)  DEFAULT NULL  COMMENT '邮箱',
    `MAIL_BIND` TINYINT(1) DEFAULT NULL COMMENT '邮箱是否已绑定',
    `IDENTITY_TYPE` VARCHAR(20)  DEFAULT NULL  COMMENT '身份类型',
    `AVATAR` VARCHAR(200)  DEFAULT NULL  COMMENT '头像',
    `SIGN` VARCHAR(100)  DEFAULT NULL  COMMENT '个性签名',
    `WECHAT_ID` VARCHAR(200)  DEFAULT NULL  COMMENT '微信ID',
    `ALIPAY_ID` VARCHAR(200)  DEFAULT NULL  COMMENT '支付宝ID',
    `WEIBO_ID` VARCHAR(200)  DEFAULT NULL  COMMENT '微博ID',
    `ROW_VERSION` BIGINT(20)  DEFAULT NULL  COMMENT '行版本',
    `IS_DELETED` TINYINT(1)  DEFAULT NULL  COMMENT '是否已删除',
    `CREATED_BY` BIGINT(20)  NOT NULL  COMMENT '创建用户',
    `CREATION_TIME` DATETIME  NOT NULL  COMMENT '创建时间',
    `LAST_UPDATED_BY` BIGINT(20)  DEFAULT NULL  COMMENT '最后更新用户',
    `LAST_UPDATE_TIME` DATETIME  DEFAULT NULL  COMMENT '最后更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';